#line 1 "DumpShaderDefinesAsCommentedCode"
// #define __SHADER_TARGET_MAJOR 6

#line 2 "DumpShaderDefinesAsCommentedCode"
// #define __SHADER_TARGET_MINOR 6

#line 3 "DumpShaderDefinesAsCommentedCode"
// #define ALLOW_STATIC_LIGHTING 1

#line 4 "DumpShaderDefinesAsCommentedCode"
// #define AMPLIFICATIONSHADER 0

#line 5 "DumpShaderDefinesAsCommentedCode"
// #define CLEAR_COAT_BOTTOM_NORMAL 0

#line 6 "DumpShaderDefinesAsCommentedCode"
// #define COMPILE_SHADERS_FOR_DEVELOPMENT 1

#line 7 "DumpShaderDefinesAsCommentedCode"
// #define COMPILER_DEFINE #define

#line 8 "DumpShaderDefinesAsCommentedCode"
// #define COMPILER_DXC 1

#line 9 "DumpShaderDefinesAsCommentedCode"
// #define COMPUTESHADER 1

#line 10 "DumpShaderDefinesAsCommentedCode"
// #define DO_CHECK 1

#line 11 "DumpShaderDefinesAsCommentedCode"
// #define DO_GUARD_SLOW 0

#line 12 "DumpShaderDefinesAsCommentedCode"
// #define DXT5_NORMALMAPS 0

#line 13 "DumpShaderDefinesAsCommentedCode"
// #define EARLY_Z_PASS_ONLY_MATERIAL_MASKING 0

#line 14 "DumpShaderDefinesAsCommentedCode"
// #define FORWARD_SHADING 0

#line 15 "DumpShaderDefinesAsCommentedCode"
// #define GBUFFER_HAS_DIFFUSE_SAMPLE_OCCLUSION 0

#line 16 "DumpShaderDefinesAsCommentedCode"
// #define GBUFFER_HAS_VELOCITY 0

#line 17 "DumpShaderDefinesAsCommentedCode"
// #define GBUFFER_REFACTOR 1

#line 18 "DumpShaderDefinesAsCommentedCode"
// #define GEOMETRYSHADER 0

#line 19 "DumpShaderDefinesAsCommentedCode"
// #define GPU_SIMULATION 1

#line 20 "DumpShaderDefinesAsCommentedCode"
// #define GPU_SIMULATION_SHADER 1

#line 21 "DumpShaderDefinesAsCommentedCode"
// #define HAS_INVERTED_Z_BUFFER 1

#line 22 "DumpShaderDefinesAsCommentedCode"
// #define INSTANCED_STEREO 0

#line 23 "DumpShaderDefinesAsCommentedCode"
// #define IRIS_NORMAL 0

#line 24 "DumpShaderDefinesAsCommentedCode"
// #define LEGACY_MATERIAL_ENERGYCONSERVATION 0

#line 25 "DumpShaderDefinesAsCommentedCode"
// #define MATERIAL_ROUGHDIFFUSE 0

#line 26 "DumpShaderDefinesAsCommentedCode"
// #define MESHSHADER 0

#line 27 "DumpShaderDefinesAsCommentedCode"
// #define MOBILE_MULTI_VIEW 0

#line 28 "DumpShaderDefinesAsCommentedCode"
// #define MULTI_VIEW 0

#line 29 "DumpShaderDefinesAsCommentedCode"
// #define NIAGARA_COMPRESSED_ATTRIBUTES_ENABLED 0

#line 30 "DumpShaderDefinesAsCommentedCode"
// #define NIAGARA_DISPATCH_INDIRECT 0

#line 31 "DumpShaderDefinesAsCommentedCode"
// #define NIAGARA_DISPATCH_TYPE 1

#line 32 "DumpShaderDefinesAsCommentedCode"
// #define NIAGARA_MAX_GPU_SPAWN_INFOS 8

#line 33 "DumpShaderDefinesAsCommentedCode"
// #define PIXELSHADER 0

#line 34 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_ALLOW_SCENE_DATA_COMPRESSED_TRANSFORMS 1

#line 35 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_BINDLESS 0

#line 36 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_BUFFER_LOAD_TYPE_CONVERSION 1

#line 37 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_CLIP_DISTANCE 1

#line 38 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_DISTANCE_FIELDS 1

#line 39 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_MESH_SHADERS_TIER0 1

#line 40 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_MESH_SHADERS_TIER1 1

#line 41 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_PER_PIXEL_DBUFFER_MASK 0

#line 42 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_RENDERTARGET_WRITE_MASK 0

#line 43 "DumpShaderDefinesAsCommentedCode"
// #define PLATFORM_SUPPORTS_UB_STRUCT 1

#line 44 "DumpShaderDefinesAsCommentedCode"
// #define POST_PROCESS_ALPHA 0

#line 45 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_ALLOW_GLOBAL_CLIP_PLANE 0

#line 46 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_MOBILE_DISABLE_VERTEX_FOG 1

#line 47 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_OIT 0

#line 48 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_STRATA_BACKCOMPATIBILITY 0

#line 49 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_SUPPORT_SKY_ATMOSPHERE 1

#line 50 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_SUPPORT_SKY_ATMOSPHERE_AFFECTS_HEIGHFOG 1

#line 51 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_SUPPORTS_LUMEN 1

#line 52 "DumpShaderDefinesAsCommentedCode"
// #define PROJECT_VERTEX_FOGGING_FOR_OPAQUE 0

#line 53 "DumpShaderDefinesAsCommentedCode"
// #define RAYCALLABLESHADER 0

#line 54 "DumpShaderDefinesAsCommentedCode"
// #define RAYGENSHADER 0

#line 55 "DumpShaderDefinesAsCommentedCode"
// #define RAYHITGROUPSHADER 0

#line 56 "DumpShaderDefinesAsCommentedCode"
// #define RAYMISSSHADER 0

#line 57 "DumpShaderDefinesAsCommentedCode"
// #define SELECTIVE_BASEPASS_OUTPUTS 0

#line 58 "DumpShaderDefinesAsCommentedCode"
// #define SHADING_PATH_DEFERRED 1

#line 59 "DumpShaderDefinesAsCommentedCode"
// #define SimulationStageIndex 2

#line 60 "DumpShaderDefinesAsCommentedCode"
// #define SM6_PROFILE 1

#line 61 "DumpShaderDefinesAsCommentedCode"
// #define STRATA_ADVANCED_DEBUG_ENABLED 0

#line 62 "DumpShaderDefinesAsCommentedCode"
// #define STRATA_ENABLED 0

#line 63 "DumpShaderDefinesAsCommentedCode"
// #define STRATA_OPAQUE_ROUGH_REFRACTION_ENABLED 0

#line 64 "DumpShaderDefinesAsCommentedCode"
// #define SUPPORT_CLOUD_SHADOW_ON_FORWARD_LIT_TRANSLUCENT 0

#line 65 "DumpShaderDefinesAsCommentedCode"
// #define SUPPORT_CLOUD_SHADOW_ON_SINGLE_LAYER_WATER 0

#line 66 "DumpShaderDefinesAsCommentedCode"
// #define SUPPORT_RECTLIGHT_ON_FORWARD_LIT_TRANSLUCENT 0

#line 67 "DumpShaderDefinesAsCommentedCode"
// #define SUPPORT_VSM_FOWARD_QUALITY 0

#line 68 "DumpShaderDefinesAsCommentedCode"
// #define THREADGROUP_SIZE 64

#line 69 "DumpShaderDefinesAsCommentedCode"
// #define THREADGROUP_SIZE_X 8

#line 70 "DumpShaderDefinesAsCommentedCode"
// #define THREADGROUP_SIZE_Y 8

#line 71 "DumpShaderDefinesAsCommentedCode"
// #define THREADGROUP_SIZE_Z 1

#line 72 "DumpShaderDefinesAsCommentedCode"
// #define UE_LWC_RENDER_TILE_SIZE 2097152.00f

#line 73 "DumpShaderDefinesAsCommentedCode"
// #define UE_LWC_RENDER_TILE_SIZE_FMOD_2PI 0.673652053f

#line 74 "DumpShaderDefinesAsCommentedCode"
// #define UE_LWC_RENDER_TILE_SIZE_FMOD_PI 0.673652053f

#line 75 "DumpShaderDefinesAsCommentedCode"
// #define UE_LWC_RENDER_TILE_SIZE_RCP 4.76837158e-07f

#line 76 "DumpShaderDefinesAsCommentedCode"
// #define UE_LWC_RENDER_TILE_SIZE_RSQRT 0.000690533954f

#line 77 "DumpShaderDefinesAsCommentedCode"
// #define UE_LWC_RENDER_TILE_SIZE_SQRT 1448.15466f

#line 78 "DumpShaderDefinesAsCommentedCode"
// #define USE_DBUFFER 1

#line 79 "DumpShaderDefinesAsCommentedCode"
// #define USE_WAVE_INTRINSICS 0

#line 80 "DumpShaderDefinesAsCommentedCode"
// #define VELOCITY_ENCODE_DEPTH 1

#line 81 "DumpShaderDefinesAsCommentedCode"
// #define VERTEXSHADER 0

#line 82 "DumpShaderDefinesAsCommentedCode"
// #define VIRTUAL_TEXTURE_ANISOTROPIC_FILTERING 0

#line 83 "DumpShaderDefinesAsCommentedCode"
// #define WORKING_COLOR_SPACE_IS_SRGB 1

#line 6 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
#pragma warning(disable:4008)

#line 110 "/Engine/Private/Random.ush"
uint3 Rand3DPCG32(int3 p)
{
	
	uint3 v = uint3(p);

	
	v = v * 1664525u + 1013904223u;

	
	v.x += v.y*v.z;
	v.y += v.z*v.x;
	v.z += v.x*v.y;

	
	v ^= v >> 16u;

	
	v.x += v.y*v.z;
	v.y += v.z*v.x;
	v.z += v.x*v.y;

	return v;
}

#line 88 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
uint3 DispatchThreadIdBounds;

#line 89 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
uint3 DispatchThreadIdToLinear;

#line 92 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint3 GDispatchThreadId;

#line 93 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint3 GGroupId;

#line 94 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint3 GGroupThreadId;

#line 95 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint  GGroupIndex;

#line 96 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint GLinearThreadId;

#line 97 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint GEmitterTickCounter;

#line 98 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint GRandomSeedOffset = 0;

#line 107 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
uint EmitterTickCounter;

#line 127 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
float NiagaraInternalNoise(uint u, uint v, uint s)
	{
		uint Seed = (u * 1664525u + v) + s + GRandomSeedOffset;
		GRandomSeedOffset += Seed;
		return float(Rand3DPCG32(int3(u,v,Seed)).x) / 4294967296.0f;
	}

#line 141 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static float Emitter_SpawnInterval;

#line 142 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static float Emitter_InterpSpawnStartDt;

#line 143 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static int Emitter_SpawnGroup;

#line 145 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static int Engine_ExecutionCount;

#line 146 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static int GGPUExecIndex;

#line 148 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
static uint GSpawnStartInstance;

#line 151 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
void SetupExecIndexForGPU()
	{
		GGPUExecIndex = GLinearThreadId;
		Engine_ExecutionCount = GSpawnStartInstance;
	}

#line 514 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
uint SimStart;

#line 529 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
RWBuffer<uint> RWInstanceCounts;

#line 540 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
int4 SimulationStageIterationInfo;

#line 547 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
int SimulationStage_GetInstanceCount() { return SimulationStageIterationInfo.x == -1 ? SimulationStageIterationInfo.y : RWInstanceCounts[SimulationStageIterationInfo.x]; }

#line 778 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
void EnterStatScope(int ID)	{}

#line 779 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
void ExitStatScope()	{}

#line 149 "/Engine/Generated/NiagaraEmitterInstance.ush"
cbuffer FNiagaraExternalParameters
{
	float Constants_Emitter_InitializeParticle_Lifetime;
	float Constants_Emitter_InitializeParticle_UniformSpriteSize;
	float Constants_Emitter_InitializeParticle_MeshUniformScale;
	float4 Constants_Emitter_InitializeParticle_PositionOffset;
	float Emitter_DistanceTraveled;
	float4 Constants_Emitter_ConvertVectorToPosition_InputPosition;
	float4 Constants_Emitter_SetVariables_F688515B4B4DD65A95AF7380AA9DD7FB_Particles_P2;
	float Constants_Emitter_Sine_Period;
	float Constants_Emitter_Sine_Scale;
	float Constants_Emitter_Sine_Bias;
	float Constants_Emitter_MakeVector_Y;
	float Constants_Emitter_MakeVector_Z;
	float Emitter_Grid2DCollection_m_height;
	float Emitter_Grid2DCollection_m_prevHeight;
	float Constants_Emitter_SetVariables_F99A54374B31E7F69D163798E3F6D4E1_Emitter_Grid2DCollection_m_height;
	float Constants_Emitter_SetVariables_7CDE55EC44D7D9067537A0B57BA508E9_Emitter_Grid2DCollection_m_prevHeight;
	float Constants_Emitter_StorePrevHeight_Intensity;
	float4 Constants_Emitter_StorePrevHeight_InputPos;
	float Emitter_SpawnRate;
}

#line 195 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Transient
{
	bool FirstFrame;
};

#line 200 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Sine
{
	float NormalizedAngle;
};

#line 205 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_SetVariables_F688515B4B4DD65A95AF7380AA9DD7FB_Particles
{
	float3 Position;
};

#line 210 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_SetVariables_F688515B4B4DD65A95AF7380AA9DD7FB
{
	FParamMap0_SetVariables_F688515B4B4DD65A95AF7380AA9DD7FB_Particles Particles;
};

#line 215 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_SetVariables_852261034DD453E1023A0E87708B3E14_Particles
{
	float3 Position;
};

#line 220 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_SetVariables_852261034DD453E1023A0E87708B3E14
{
	FParamMap0_SetVariables_852261034DD453E1023A0E87708B3E14_Particles Particles;
};

#line 225 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_ParticleState
{
	float DeltaTime;
	float Lifetime;
};

#line 231 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Particles_Previous
{
	float3 P2;
	float3 Position;
	float3 Scale;
	float2 SpriteSize;
};

#line 239 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Particles
{
	float Age;
	float Lifetime;
	float Mass;
	float MaterialRandom;
	float NormalizedAge;
	float3 P2;
	float3 Position;
	FParamMap0_Particles_Previous Previous;
	float RibbonUVDistance;
	float3 Scale;
	float2 SpriteSize;
	int UniqueID;
};

#line 255 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_OUTPUT_VAR_ParticleState
{
	bool FirstFrame;
};

#line 260 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_OUTPUT_VAR
{
	FParamMap0_OUTPUT_VAR_ParticleState ParticleState;
};

#line 265 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_MakeVector
{
	float X;
};

#line 270 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Local_InitializeParticle
{
	float InitRIbbonDistance;
};

#line 275 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Local
{
	FParamMap0_Local_InitializeParticle InitializeParticle;
};

#line 280 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Interpolation
{
	float Emitter_InterpSpawnStartDt;
	int Emitter_SpawnGroup;
	float Emitter_SpawnInterval;
	int InterpSpawn_Index;
	float InterpSpawn_InvSpawnTime;
	float InterpSpawn_InvUpdateTime;
	float InterpSpawn_SpawnTime;
	float InterpSpawn_UpdateTime;
	float SpawnInterp;
};

#line 293 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_InitializeParticle
{
	float MaterialRandom;
	int PositionOffsetCoordinateSpace;
};

#line 299 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Engine_System
{
	float Age;
	int CurrentTimeStep;
	int NumEmitters;
	int NumEmittersAlive;
	int NumParticles;
	int NumTimeSteps;
	int PaddingInt32_0;
	int PaddingInt32_1;
	int RandomSeed;
	int SignificanceIndex;
	int TickCount;
	float TimeStepFraction;
};

#line 315 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Engine_Owner
{
	int ExecutionState;
	float LODDistance;
	float LODDistanceFraction;
	float4 LWCTile;
	int PaddingInt32_0;
	int PaddingInt32_1;
	int PaddingInt32_2;
	int PaddingInt32_3;
	int PaddingInt32_4;
	int PaddingInt32_5;
	float3 Position;
	float4 Rotation;
	float3 Scale;
	float4x4 SystemLocalToWorld;
	float4x4 SystemLocalToWorldNoScale;
	float4x4 SystemLocalToWorldTransposed;
	float4x4 SystemWorldToLocal;
	float4x4 SystemWorldToLocalNoScale;
	float4x4 SystemWorldToLocalTransposed;
	float3 SystemXAxis;
	float3 SystemYAxis;
	float3 SystemZAxis;
	float TimeSinceRendered;
	float3 Velocity;
};

#line 343 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Engine_Emitter
{
	int InstanceSeed;
	int NumParticles;
	int PaddingInt32_0;
	int PaddingInt32_1;
	float SpawnCountScale;
	int TotalSpawnedParticles;
};

#line 353 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Engine
{
	float DeltaTime;
	FParamMap0_Engine_Emitter Emitter;
	int ExecutionCount;
	float InverseDeltaTime;
	FParamMap0_Engine_Owner Owner;
	int PaddingInt32_0;
	int PaddingInt32_1;
	int QualityLevel;
	float RealTime;
	FParamMap0_Engine_System System;
	float Time;
	float WorldDeltaTime;
};

#line 369 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Emitter_Grid2DCollection
{
	float m_height;
	float m_prevHeight;
};

#line 375 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Emitter
{
	float Age;
	float DistanceTraveled;
	FParamMap0_Emitter_Grid2DCollection Grid2DCollection;
	int RandomSeed;
	float SpawnRate;
};

#line 384 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_DataInstance
{
	bool Alive;
};

#line 389 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_ConvertVectorToPosition001
{
	float3 InputPosition;
};

#line 394 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Array_Previous
{
	int P2;
	int Position;
	int Scale;
	int SpriteSize;
};

#line 402 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0_Array
{
	int Age;
	int Lifetime;
	int Mass;
	int MaterialRandom;
	int NormalizedAge;
	int P2;
	int Position;
	FParamMap0_Array_Previous Previous;
	int RibbonUVDistance;
	int Scale;
	int SpriteSize;
	int UniqueID;
};

#line 418 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FParamMap0
{
	FParamMap0_Array Array;
	FParamMap0_ConvertVectorToPosition001 ConvertVectorToPosition001;
	FParamMap0_DataInstance DataInstance;
	FParamMap0_Emitter Emitter;
	FParamMap0_Engine Engine;
	FParamMap0_InitializeParticle InitializeParticle;
	FParamMap0_Interpolation Interpolation;
	FParamMap0_Local Local;
	FParamMap0_MakeVector MakeVector;
	FParamMap0_OUTPUT_VAR OUTPUT_VAR;
	FParamMap0_Particles Particles;
	FParamMap0_ParticleState ParticleState;
	FParamMap0_SetVariables_852261034DD453E1023A0E87708B3E14 SetVariables_852261034DD453E1023A0E87708B3E14;
	FParamMap0_SetVariables_F688515B4B4DD65A95AF7380AA9DD7FB SetVariables_F688515B4B4DD65A95AF7380AA9DD7FB;
	FParamMap0_Sine Sine;
	FParamMap0_Transient Transient;
};

#line 438 "/Engine/Generated/NiagaraEmitterInstance.ush"
struct FSimulationContext
{










	FParamMap0 MapSimStage2_PrevFrame;







};

#line 473 "/Engine/Generated/NiagaraEmitterInstance.ush"
void ExecutionIndexToGridIndex_Emitter_Grid2DCollection(out int Out_IndexX, out int Out_IndexY);

#line 474 "/Engine/Generated/NiagaraEmitterInstance.ush"
void SetFloatValue_Emitter_Grid2DCollection_UEImpureCall_Attributem_height(int In_IndexX, int In_IndexY, float In_Value);

#line 479 "/Engine/Generated/NiagaraEmitterInstance.ush"
void GetPreviousFloatValue_Emitter_Grid2DCollection_Attributem_height(int In_IndexX, int In_IndexY, out float Out_Value);

#line 480 "/Engine/Generated/NiagaraEmitterInstance.ush"
void ExecutionIndexToUnit_Emitter_Grid2DCollection(out float2 Out_Unit);

#line 481 "/Engine/Generated/NiagaraEmitterInstance.ush"
void GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePosition(int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);

#line 482 "/Engine/Generated/NiagaraEmitterInstance.ush"
void NiagaraScript_167_Particle_ClampResults_true_Func_(float In_Value, float In_InputMin, float In_InputMax, float In_OutputMin, float In_OutputMax, out float Out_NewOutput, inout FSimulationContext Context);

#line 483 "/Engine/Generated/NiagaraEmitterInstance.ush"
void NiagaraScript_168_Particle_ClampResults_true_Func_(float In_Value, float In_InputMin, float In_InputMax, float In_OutputMin, float In_OutputMax, out float Out_NewOutput, inout FSimulationContext Context);

#line 484 "/Engine/Generated/NiagaraEmitterInstance.ush"
void Gradient8EB9FC5248A1A42AB5E8EE95213FA2C2_Func_(float2 In_Unit, float2 In_InputPos, float In_Intensity, out float Out_mask);

#line 485 "/Engine/Generated/NiagaraEmitterInstance.ush"
void StorePrevHeight_Emitter_Func_(inout FSimulationContext Context);

#line 666 "/Engine/Generated/NiagaraEmitterInstance.ush"
void NiagaraScript_167_Particle_ClampResults_true_Func_(float In_Value, float In_InputMin, float In_InputMax, float In_OutputMin, float In_OutputMax, out float Out_NewOutput, inout FSimulationContext Context)
{
	float Result17 = In_Value - In_InputMin;
	float Result18 = In_InputMax - In_InputMin;
	float Result19 = Result17 / Result18;
	float Constant35 = 0;
	float Constant36 = 1;
	float Result20 = clamp(Result19,Constant35,Constant36);
	float Result21 = lerp(In_OutputMin,In_OutputMax,Result20);
	Out_NewOutput = Result21;
}

#line 680 "/Engine/Generated/NiagaraEmitterInstance.ush"
void NiagaraScript_168_Particle_ClampResults_true_Func_(float In_Value, float In_InputMin, float In_InputMax, float In_OutputMin, float In_OutputMax, out float Out_NewOutput, inout FSimulationContext Context)
{
	float Result22 = In_Value - In_InputMin;
	float Result23 = In_InputMax - In_InputMin;
	float Result24 = Result22 / Result23;
	float Constant41 = 0;
	float Constant42 = 1;
	float Result25 = clamp(Result24,Constant41,Constant42);
	float Result26 = lerp(In_OutputMin,In_OutputMax,Result25);
	Out_NewOutput = Result26;
}

#line 694 "/Engine/Generated/NiagaraEmitterInstance.ush"
void Gradient8EB9FC5248A1A42AB5E8EE95213FA2C2_Func_(float2 In_Unit, float2 In_InputPos, float In_Intensity, out float Out_mask)
{

Out_mask = 1 - smoothstep(0,0.15,distance(In_Unit,In_InputPos));
	Out_mask*=In_Intensity;
	float2 other =float2(.1,.9);
	Out_mask += 1 - smoothstep(0,0.15,distance(In_Unit,other);
}

#line 705 "/Engine/Generated/NiagaraEmitterInstance.ush"
void StorePrevHeight_Emitter_Func_(inout FSimulationContext Context)
{
	int ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexX1;
	int ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexY1;
	ExecutionIndexToGridIndex_Emitter_Grid2DCollection(ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexX1, ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexY1);
	float GetPreviousFloatValue_Emitter_Grid2DCollection_Attributem_heightOutput_Value;
	GetPreviousFloatValue_Emitter_Grid2DCollection_Attributem_height(ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexX1, ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexY1, GetPreviousFloatValue_Emitter_Grid2DCollection_Attributem_heightOutput_Value);
	float2 ExecutionIndexToUnit_Emitter_Grid2DCollectionOutput_Unit;
	ExecutionIndexToUnit_Emitter_Grid2DCollection(ExecutionIndexToUnit_Emitter_Grid2DCollectionOutput_Unit);
	int Constant30 = 0;
	bool GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePositionOutput_Valid;
	float3 GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePositionOutput_Value;
	GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePosition(Constant30, GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePositionOutput_Valid, GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePositionOutput_Value);
	float X;
	float Y;
	float Z;
	X = GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePositionOutput_Value.x;
	Y = GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePositionOutput_Value.y;
	Z = GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePositionOutput_Value.z;
	float Constant31 = -100;
	float Output13;
	Output13 = Constant31;
	float Constant32 = 100;
	float Output14;
	Output14 = Constant32;
	float Constant33 = 0;
	float Output15;
	Output15 = Constant33;
	float Constant34 = 1;
	float Output16;
	Output16 = Constant34;
	float NiagaraScript_167_Particle_ClampResults_true_Func_Output_NewOutput;
	NiagaraScript_167_Particle_ClampResults_true_Func_(X, Output13, Output14, Output15, Output16, NiagaraScript_167_Particle_ClampResults_true_Func_Output_NewOutput, Context);
	float Constant37 = -100;
	float Output17;
	Output17 = Constant37;
	float Constant38 = 100;
	float Output18;
	Output18 = Constant38;
	float Constant39 = 0;
	float Output19;
	Output19 = Constant39;
	float Constant40 = 1;
	float Output110;
	Output110 = Constant40;
	float NiagaraScript_168_Particle_ClampResults_true_Func_Output_NewOutput;
	NiagaraScript_168_Particle_ClampResults_true_Func_(Y, Output17, Output18, Output19, Output110, NiagaraScript_168_Particle_ClampResults_true_Func_Output_NewOutput, Context);
	float2 Output111;
	Output111.x = NiagaraScript_167_Particle_ClampResults_true_Func_Output_NewOutput;
	Output111.y = NiagaraScript_168_Particle_ClampResults_true_Func_Output_NewOutput;
	float Gradient8EB9FC5248A1A42AB5E8EE95213FA2C2_Func_Output_mask;
	Gradient8EB9FC5248A1A42AB5E8EE95213FA2C2_Func_(ExecutionIndexToUnit_Emitter_Grid2DCollectionOutput_Unit, Output111, Constants_Emitter_StorePrevHeight_Intensity, Gradient8EB9FC5248A1A42AB5E8EE95213FA2C2_Func_Output_mask);
	float Result27 = GetPreviousFloatValue_Emitter_Grid2DCollection_Attributem_heightOutput_Value + Gradient8EB9FC5248A1A42AB5E8EE95213FA2C2_Func_Output_mask;
	SetFloatValue_Emitter_Grid2DCollection_UEImpureCall_Attributem_height(ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexX1, ExecutionIndexToGridIndex_Emitter_Grid2DCollectionOutput_IndexY1, Result27);
}

#line 850 "/Engine/Generated/NiagaraEmitterInstance.ush"
void ReadDataSets(inout FSimulationContext Context)
{
}

#line 854 "/Engine/Generated/NiagaraEmitterInstance.ush"
void WriteDataSets(inout FSimulationContext Context)
{
}

#line 968 "/Engine/Generated/NiagaraEmitterInstance.ush"
void SimulateMapSimStage2_PrevFrame(inout FSimulationContext Context)
{
	
	EnterStatScope(8 );
	StorePrevHeight_Emitter_Func_(Context);
	ExitStatScope();
	


}

#line 1005 "/Engine/Generated/NiagaraEmitterInstance.ush"
float2 Emitter_Grid2DCollection_UnitToUV;

#line 1009 "/Engine/Generated/NiagaraEmitterInstance.ush"
Texture2DArray<float> Emitter_Grid2DCollection_Grid;

#line 1010 "/Engine/Generated/NiagaraEmitterInstance.ush"
RWTexture2DArray<float> Emitter_Grid2DCollection_OutputGrid;

#line 1014 "/Engine/Generated/NiagaraEmitterInstance.ush"
uint			Emitter_StorePrevHeight_ParticleAttributeReader_InstanceCountOffset;

#line 1014 "/Engine/Generated/NiagaraEmitterInstance.ush"
uint			Emitter_StorePrevHeight_ParticleAttributeReader_ParticleStrideFloat;

#line 1014 "/Engine/Generated/NiagaraEmitterInstance.ush"
Buffer<float>	Emitter_StorePrevHeight_ParticleAttributeReader_InputFloatBuffer;

#line 1014 "/Engine/Generated/NiagaraEmitterInstance.ush"
int4			Emitter_StorePrevHeight_ParticleAttributeReader_AttributeIndices[1];

#line 1076 "/Engine/Generated/NiagaraEmitterInstance.ush"
void ExecutionIndexToGridIndex_Emitter_Grid2DCollection(out int Out_IndexX, out int Out_IndexY)
			{
				
					Out_IndexX = GDispatchThreadId.x;
					Out_IndexY = GDispatchThreadId.y;
				




			}

#line 1088 "/Engine/Generated/NiagaraEmitterInstance.ush"
void SetFloatValue_Emitter_Grid2DCollection_UEImpureCall_Attributem_height(int In_IndexX, int In_IndexY, float In_Value)
			{
				int In_AttributeIndex = 0;

					Emitter_Grid2DCollection_OutputGrid[int3(In_IndexX, In_IndexY, In_AttributeIndex)] = In_Value;

			}

#line 1104 "/Engine/Generated/NiagaraEmitterInstance.ush"
void GetPreviousFloatValue_Emitter_Grid2DCollection_Attributem_height(int In_IndexX, int In_IndexY, out float Out_Val)
			{
				int In_AttributeIndex = 0;

						Out_Val = Emitter_Grid2DCollection_Grid.Load(int4(In_IndexX, In_IndexY, In_AttributeIndex, 0));

	}

#line 1112 "/Engine/Generated/NiagaraEmitterInstance.ush"
void ExecutionIndexToUnit_Emitter_Grid2DCollection(out float2 Out_Unit)
			{
				
					Out_Unit = (float2(GDispatchThreadId.x, GDispatchThreadId.y) + .5) * Emitter_Grid2DCollection_UnitToUV;			
				





			}

#line 1123 "/Engine/Generated/NiagaraEmitterInstance.ush"
void GetPositionByIndex_Emitter_StorePrevHeight_ParticleAttributeReader_AttributePosition(int ParticleIndex, out bool Out_Valid, out float3 Out_Value)
{
    int RegisterIndex = Emitter_StorePrevHeight_ParticleAttributeReader_AttributeIndices[0].x;
    int NumParticles = Emitter_StorePrevHeight_ParticleAttributeReader_InstanceCountOffset != 0xffffffff ? RWInstanceCounts[Emitter_StorePrevHeight_ParticleAttributeReader_InstanceCountOffset] : 0;
    if(RegisterIndex != -1 && ParticleIndex >= 0 && ParticleIndex < NumParticles)
    {
        Out_Valid = true;










        {
                Out_Value.x = float(Emitter_StorePrevHeight_ParticleAttributeReader_InputFloatBuffer[(RegisterIndex + 0)*Emitter_StorePrevHeight_ParticleAttributeReader_ParticleStrideFloat + ParticleIndex]);
                Out_Value.y = float(Emitter_StorePrevHeight_ParticleAttributeReader_InputFloatBuffer[(RegisterIndex + 1)*Emitter_StorePrevHeight_ParticleAttributeReader_ParticleStrideFloat + ParticleIndex]);
                Out_Value.z = float(Emitter_StorePrevHeight_ParticleAttributeReader_InputFloatBuffer[(RegisterIndex + 2)*Emitter_StorePrevHeight_ParticleAttributeReader_ParticleStrideFloat + ParticleIndex]);
        }
    }
    else
    {
        Out_Valid = false;
        Out_Value = (float3)0;
    }
}

#line 1205 "/Engine/Generated/NiagaraEmitterInstance.ush"
void SetupFromIterationSource_MapSimStage2_PrevFrame_GeneratedSetup_Func_(inout FSimulationContext Context)
{

	
		
		
	

}

#line 1214 "/Engine/Generated/NiagaraEmitterInstance.ush"
void SetupFromIterationSource_MapSimStage2_PrevFrame(inout FSimulationContext Context)
{

	SetupFromIterationSource_MapSimStage2_PrevFrame_GeneratedSetup_Func_(Context);

}

#line 1222 "/Engine/Generated/NiagaraEmitterInstance.ush"
void TeardownFromIterationSource_MapSimStage2_PrevFrame_GeneratedTeardown_Func_(inout FSimulationContext Context)
{

	
	

}

#line 1229 "/Engine/Generated/NiagaraEmitterInstance.ush"
void TeardownFromIterationSource_MapSimStage2_PrevFrame(inout FSimulationContext Context)
{

	TeardownFromIterationSource_MapSimStage2_PrevFrame_GeneratedTeardown_Func_(Context);

}

#line 1242 "/Engine/Generated/NiagaraEmitterInstance.ush"
void InitConstants(inout FSimulationContext Context)
{























}

#line 1269 "/Engine/Generated/NiagaraEmitterInstance.ush"
void InitSpawnVariables(inout FSimulationContext Context)
{
#line 1303 "/Engine/Generated/NiagaraEmitterInstance.ush"

}

#line 1306 "/Engine/Generated/NiagaraEmitterInstance.ush"
void LoadUpdateVariables(inout FSimulationContext Context, int InstanceIdx)
{
#line 1346 "/Engine/Generated/NiagaraEmitterInstance.ush"

SetupFromIterationSource_MapSimStage2_PrevFrame(Context);


}

#line 1357 "/Engine/Generated/NiagaraEmitterInstance.ush"
void TransferAttributes(inout FSimulationContext Context)
{








}

#line 1369 "/Engine/Generated/NiagaraEmitterInstance.ush"
void StoreUpdateVariables(in FSimulationContext Context, bool bIsValidInstance)
{
#line 1412 "/Engine/Generated/NiagaraEmitterInstance.ush"

if ( bIsValidInstance )
{
	TeardownFromIterationSource_MapSimStage2_PrevFrame(Context);

}


}

#line 1432 "/Engine/Generated/NiagaraEmitterInstance.ush"
[numthreads(8, 8, 1)]
void SimulateMainComputeCS(
	uint3 InDispatchThreadId	: SV_DispatchThreadID,
	uint3 InGroupId				: SV_GroupID,
	uint3 InGroupThreadId		: SV_GroupThreadID,
	uint  InGroupIndex			: SV_GroupIndex)
{
	GDispatchThreadId	= InDispatchThreadId;
	GGroupId			= InGroupId;
	GGroupThreadId		= InGroupThreadId;
	GGroupIndex			= InGroupIndex;
	GEmitterTickCounter = EmitterTickCounter;
	GRandomSeedOffset = 0;
#line 1557 "/Engine/Generated/NiagaraEmitterInstance.ush"











	GLinearThreadId		= GDispatchThreadId.x + (GDispatchThreadId.y * DispatchThreadIdToLinear.y);
	




	const uint MaxInstances = SimulationStage_GetInstanceCount();
	GLinearThreadId = all(GDispatchThreadId < DispatchThreadIdBounds) ? GLinearThreadId : MaxInstances;
	GSpawnStartInstance = MaxInstances;
	const bool bRunUpdateLogic = (GLinearThreadId < GSpawnStartInstance) && (SimStart != 1);
	const bool bRunSpawnLogic = (GLinearThreadId < GSpawnStartInstance) && (SimStart == 1);
	
	const float RandomSeedInitialisation = NiagaraInternalNoise(GLinearThreadId * 16384, 0 * 8196, (bRunUpdateLogic ? 4096 : 0) + EmitterTickCounter);	
	
	FSimulationContext Context = (FSimulationContext)0;
	[branch]
	if (bRunUpdateLogic)
	{
		SetupExecIndexForGPU();
		InitConstants(Context);
		LoadUpdateVariables(Context, GLinearThreadId);
		ReadDataSets(Context);
	}
	else if (bRunSpawnLogic)
	{
		SetupExecIndexForGPU();
		InitConstants(Context);
		InitSpawnVariables(Context);
		ReadDataSets(Context);
		TransferAttributes(Context);
	}

	if (bRunUpdateLogic || bRunSpawnLogic)
	{
		SimulateMapSimStage2_PrevFrame(Context);
		WriteDataSets(Context);
	}

	StoreUpdateVariables(Context, bRunUpdateLogic || bRunSpawnLogic);

#line 1710 "/Engine/Generated/NiagaraEmitterInstance.ush"

}



#if 0 /*BEGIN_RESOURCE_TABLES*/
View, 376963194
Strata, 158337041
DrawRectangleParameters, 3145984
InstancedView, 450888449
MobileSceneTextures, 147131313
SceneTexturesStruct, 158338568
StrataPublic, 1048841
NULL, 0
View_MaterialTextureBilinearWrapedSampler, View, 8, 0
View_MaterialTextureBilinearClampedSampler, View, 8, 1
View_VolumetricLightmapIndirectionTexture, View, 5, 2
View_VolumetricLightmapBrickAmbientVector, View, 5, 3
View_VolumetricLightmapBrickSHCoefficients0, View, 5, 4
View_VolumetricLightmapBrickSHCoefficients1, View, 5, 5
View_VolumetricLightmapBrickSHCoefficients2, View, 5, 6
View_VolumetricLightmapBrickSHCoefficients3, View, 5, 7
View_VolumetricLightmapBrickSHCoefficients4, View, 5, 8
View_VolumetricLightmapBrickSHCoefficients5, View, 5, 9
View_SkyBentNormalBrickTexture, View, 5, 10
View_DirectionalLightShadowingBrickTexture, View, 5, 11
View_VolumetricLightmapBrickAmbientVectorSampler, View, 8, 12
View_VolumetricLightmapTextureSampler0, View, 8, 13
View_VolumetricLightmapTextureSampler1, View, 8, 14
View_VolumetricLightmapTextureSampler2, View, 8, 15
View_VolumetricLightmapTextureSampler3, View, 8, 16
View_VolumetricLightmapTextureSampler4, View, 8, 17
View_VolumetricLightmapTextureSampler5, View, 8, 18
View_SkyBentNormalTextureSampler, View, 8, 19
View_DirectionalLightShadowingTextureSampler, View, 8, 20
View_GlobalDistanceFieldPageAtlasTexture, View, 5, 21
View_GlobalDistanceFieldCoverageAtlasTexture, View, 5, 22
View_GlobalDistanceFieldPageTableTexture, View, 5, 23
View_GlobalDistanceFieldMipTexture, View, 5, 24
View_GlobalDistanceFieldPageAtlasTextureSampler, View, 8, 25
View_GlobalDistanceFieldCoverageAtlasTextureSampler, View, 8, 26
View_GlobalDistanceFieldMipTextureSampler, View, 8, 27
View_AtmosphereTransmittanceTexture, View, 5, 28
View_AtmosphereTransmittanceTextureSampler, View, 8, 29
View_AtmosphereIrradianceTexture, View, 5, 30
View_AtmosphereIrradianceTextureSampler, View, 8, 31
View_AtmosphereInscatterTexture, View, 5, 32
View_AtmosphereInscatterTextureSampler, View, 8, 33
View_PerlinNoiseGradientTexture, View, 5, 34
View_PerlinNoiseGradientTextureSampler, View, 8, 35
View_PerlinNoise3DTexture, View, 5, 36
View_PerlinNoise3DTextureSampler, View, 8, 37
View_SobolSamplingTexture, View, 5, 38
View_SharedPointWrappedSampler, View, 8, 39
View_SharedPointClampedSampler, View, 8, 40
View_SharedBilinearWrappedSampler, View, 8, 41
View_SharedBilinearClampedSampler, View, 8, 42
View_SharedBilinearAnisoClampedSampler, View, 8, 43
View_SharedTrilinearWrappedSampler, View, 8, 44
View_SharedTrilinearClampedSampler, View, 8, 45
View_PreIntegratedBRDF, View, 5, 46
View_PreIntegratedBRDFSampler, View, 8, 47
View_SkyIrradianceEnvironmentMap, View, 6, 48
View_TransmittanceLutTexture, View, 5, 49
View_TransmittanceLutTextureSampler, View, 8, 50
View_SkyViewLutTexture, View, 5, 51
View_SkyViewLutTextureSampler, View, 8, 52
View_DistantSkyLightLutTexture, View, 5, 53
View_DistantSkyLightLutTextureSampler, View, 8, 54
View_CameraAerialPerspectiveVolume, View, 5, 55
View_CameraAerialPerspectiveVolumeSampler, View, 8, 56
View_CameraAerialPerspectiveVolumeMieOnly, View, 5, 57
View_CameraAerialPerspectiveVolumeMieOnlySampler, View, 8, 58
View_CameraAerialPerspectiveVolumeRayOnly, View, 5, 59
View_CameraAerialPerspectiveVolumeRayOnlySampler, View, 8, 60
View_HairScatteringLUTTexture, View, 5, 61
View_HairScatteringLUTSampler, View, 8, 62
View_GGXLTCMatTexture, View, 5, 63
View_GGXLTCMatSampler, View, 8, 64
View_GGXLTCAmpTexture, View, 5, 65
View_GGXLTCAmpSampler, View, 8, 66
View_SheenLTCTexture, View, 5, 67
View_SheenLTCSampler, View, 8, 68
View_ShadingEnergyGGXSpecTexture, View, 5, 69
View_ShadingEnergyGGXGlassTexture, View, 5, 70
View_ShadingEnergyClothSpecTexture, View, 5, 71
View_ShadingEnergyDiffuseTexture, View, 5, 72
View_ShadingEnergySampler, View, 8, 73
View_GlintTexture, View, 5, 74
View_GlintSampler, View, 8, 75
View_SimpleVolumeTexture, View, 5, 76
View_SimpleVolumeTextureSampler, View, 8, 77
View_SimpleVolumeEnvTexture, View, 5, 78
View_SimpleVolumeEnvTextureSampler, View, 8, 79
View_SSProfilesTexture, View, 5, 80
View_SSProfilesSampler, View, 8, 81
View_SSProfilesTransmissionSampler, View, 8, 82
View_SSProfilesPreIntegratedTexture, View, 5, 83
View_SSProfilesPreIntegratedSampler, View, 8, 84
View_SpecularProfileTexture, View, 5, 85
View_SpecularProfileSampler, View, 8, 86
View_WaterIndirection, View, 6, 87
View_WaterData, View, 6, 88
View_RectLightAtlasTexture, View, 5, 89
View_RectLightAtlasSampler, View, 8, 90
View_IESAtlasTexture, View, 5, 91
View_IESAtlasSampler, View, 8, 92
View_LandscapeWeightmapSampler, View, 8, 93
View_LandscapeIndirection, View, 6, 94
View_LandscapePerComponentData, View, 6, 95
View_VTFeedbackBuffer, View, 7, 96
View_PhysicsFieldClipmapBuffer, View, 6, 97
Strata_MaterialTextureArray, Strata, 9, 0
Strata_TopLayerTexture, Strata, 9, 1
Strata_OpaqueRoughRefractionTexture, Strata, 9, 2
Strata_BSDFOffsetTexture, Strata, 9, 3
Strata_BSDFTileTexture, Strata, 9, 4
Strata_BSDFTileCountBuffer, Strata, 16, 5
MobileSceneTextures_SceneColorTexture, MobileSceneTextures, 9, 0
MobileSceneTextures_SceneColorTextureSampler, MobileSceneTextures, 8, 1
MobileSceneTextures_SceneDepthTexture, MobileSceneTextures, 9, 2
MobileSceneTextures_SceneDepthTextureSampler, MobileSceneTextures, 8, 3
MobileSceneTextures_ScenePartialDepthTexture, MobileSceneTextures, 9, 4
MobileSceneTextures_ScenePartialDepthTextureSampler, MobileSceneTextures, 8, 5
MobileSceneTextures_CustomDepthTexture, MobileSceneTextures, 9, 6
MobileSceneTextures_CustomDepthTextureSampler, MobileSceneTextures, 8, 7
MobileSceneTextures_CustomStencilTexture, MobileSceneTextures, 12, 8
MobileSceneTextures_SceneVelocityTexture, MobileSceneTextures, 9, 9
MobileSceneTextures_SceneVelocityTextureSampler, MobileSceneTextures, 8, 10
MobileSceneTextures_GBufferATexture, MobileSceneTextures, 9, 11
MobileSceneTextures_GBufferBTexture, MobileSceneTextures, 9, 12
MobileSceneTextures_GBufferCTexture, MobileSceneTextures, 9, 13
MobileSceneTextures_GBufferDTexture, MobileSceneTextures, 9, 14
MobileSceneTextures_SceneDepthAuxTexture, MobileSceneTextures, 9, 15
MobileSceneTextures_LocalLightTextureA, MobileSceneTextures, 9, 16
MobileSceneTextures_LocalLightTextureB, MobileSceneTextures, 9, 17
MobileSceneTextures_GBufferATextureSampler, MobileSceneTextures, 8, 18
MobileSceneTextures_GBufferBTextureSampler, MobileSceneTextures, 8, 19
MobileSceneTextures_GBufferCTextureSampler, MobileSceneTextures, 8, 20
MobileSceneTextures_GBufferDTextureSampler, MobileSceneTextures, 8, 21
MobileSceneTextures_SceneDepthAuxTextureSampler, MobileSceneTextures, 8, 22
SceneTexturesStruct_SceneColorTexture, SceneTexturesStruct, 9, 0
SceneTexturesStruct_SceneDepthTexture, SceneTexturesStruct, 9, 1
SceneTexturesStruct_ScenePartialDepthTexture, SceneTexturesStruct, 9, 2
SceneTexturesStruct_GBufferATexture, SceneTexturesStruct, 9, 3
SceneTexturesStruct_GBufferBTexture, SceneTexturesStruct, 9, 4
SceneTexturesStruct_GBufferCTexture, SceneTexturesStruct, 9, 5
SceneTexturesStruct_GBufferDTexture, SceneTexturesStruct, 9, 6
SceneTexturesStruct_GBufferETexture, SceneTexturesStruct, 9, 7
SceneTexturesStruct_GBufferFTexture, SceneTexturesStruct, 9, 8
SceneTexturesStruct_GBufferVelocityTexture, SceneTexturesStruct, 9, 9
SceneTexturesStruct_ScreenSpaceAOTexture, SceneTexturesStruct, 9, 10
SceneTexturesStruct_CustomDepthTexture, SceneTexturesStruct, 9, 11
SceneTexturesStruct_CustomStencilTexture, SceneTexturesStruct, 12, 12
SceneTexturesStruct_PointClampSampler, SceneTexturesStruct, 8, 13
StrataPublic_TopLayerTexture, StrataPublic, 9, 0
NULL, NULL, 0, 0
#endif /*END_RESOURCE_TABLES*/
#if 0 /*DIRECT COMPILE*/
-directcompile -format=PCD3D_SM6 -entry=SimulateMainComputeCS -shaderPlatformName=PCD3D_SM6 -cs C:/Users/madar/Desktop/AJ/Proyectos Personales/UnrealEffects/UnrealEffects/Saved/ShaderDebugInfo/PCD3D_SM6/PartOverWater/Init_RT/ParticleGPUComputeScript/FNiagaraShader/2/NiagaraEmitterInstanceShader.usf -cflags=8590987264 -nocrashreports
#endif /*DIRECT COMPILE*/
